# Generated by Django 6.0 on 2026-01-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0002_alter_activitylog_action_alter_activitylog_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='task_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
