# Generated by Django 6.0 on 2026-01-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activityLog', '0003_activitylog_task_title'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='category_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
